language: python
# command to install dependencies
addons:
    apt:
        packages:
            - cmake
install:
  - pip install scipy numpy
  - pip install pytest pytest-cov
  - python setup.py install
# command to run tests
script: 
  - pytest --cov=./tests tests
